development:
  adapter: postgresql
  encoding: unicode
  database: api_app_jwt
  host: localhost
  pool: 5
  username: rails_dev
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: api_app_jwt_test
  host: localhost
  pool: 5
  username: rails_dev
  password: 123